version: "3"
services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD='root_pass'
      - MYSQL_DATABASE='query_forum'
      - MYSQL_USER='db_user'
      - MYSQL_PASSWORD='user_pass'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - net

  java-war-application:
    image: query_forum
    restart: always
    depends_on:
      - mysql-docker-container
    ports:
      - 8056:8055
    expose:
      - '8055'
    networks:
      - net
    command: java -jar package.war

volumes:
  my-db: {}

networks:
  net: