version: "3"
services:
  mysql-docker-container:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD='root_pass'
      - MYSQL_DATABASE='query_forum'
      - MYSQL_USER='db_user'
      - MYSQL_PASSWORD='user_pass'
    ports:
      - 3307:3306
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - net
#    command: mysql_upgrade

  java-war-application:
    image: query_forum
    restart: always
    depends_on:
      - mysql-docker-container
    ports:
      - 8056:8080
    expose:
      - '8080'
    networks:
      - net
#    command: java -jar queryForum.war

volumes:
  my-db:

networks:
  net: